### ISSUE TITLE
[Android] A crash in com.mapswithme.util.ThemeUtils.isValidTheme(ThemeUtils.java:82)

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#113]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference
       at com.mapswithme.util.ThemeUtils.isValidTheme(ThemeUtils.java:82)
       at com.mapswithme.util.Config.getUiThemeSettings(Config.java:235)
       at com.mapswithme.util.ThemeSwitcher.restart(ThemeSwitcher.java:86)
       at com.mapswithme.maps.MwmApplication.initNativeFramework(MwmApplication.java:262)
       at com.mapswithme.maps.MwmApplication.initCore(MwmApplication.java:195)
       at com.mapswithme.maps.SplashActivity.init(SplashActivity.java:501)
       at com.mapswithme.maps.SplashActivity.access$500(SplashActivity.java:41)
       at com.mapswithme.maps.SplashActivity$4.run(SplashActivity.java:133)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
 ```
 
 https://console.firebase.google.com/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/9c949c803fe4ecb6e58310ffb10a6809?time=last-seven-days&sessionEventKey=601A46F2014F00016EC3FB7FB84AF2E3_1503371109559089510

**Comment by rtsisyk** [comment]
This problem happened during development. Thus, this bug is not a bug at all.
