### ISSUE TITLE
[Android] A crash in  com.mapswithme.maps.widget.menu.NavMenu.show (NavMenu.java:289)

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#114]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
       at com.mapswithme.util.UiUtils.showIf(UiUtils.java:232)
       at com.mapswithme.maps.widget.menu.NavMenu.show(NavMenu.java:289)
       at com.mapswithme.maps.routing.NavigationController.show(NavigationController.java:358)
       at com.mapswithme.maps.MwmActivity.showNavigation(MwmActivity.java:2244)
       at com.mapswithme.maps.routing.RoutingController.restore(RoutingController.java:320)
       at com.mapswithme.maps.MwmActivity.onResumeFragments(MwmActivity.java:1483)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
       at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:204)
       at com.mapswithme.maps.base.BaseMwmFragmentActivity.onPostResume(BaseMwmFragmentActivity.java:233)
       at android.app.Activity.performResume(Activity.java:7220)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3667)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2901)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

https://console.firebase.google.com/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/30f59b42f8717492b45c1835b43ac1e5?time=last-seven-days&sessionEventKey=6012B1FD00920001316D02083B8A7D8D_1501236924477959664

**Comment by rtsisyk** [comment]
This problem happened during development. Thus, this bug is not a bug at all.
