### ISSUE TITLE
[Android] A crash in GetAdInfoTask.doInBackground

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#117]
```
Non-fatal Exception: java.util.concurrent.TimeoutException: Advertising id wasn't obtained within 4000 ms
       at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:312)
       at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:255)
       at android.os.AsyncTask$3.call(AsyncTask.java:378)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

https://console.firebase.google.com/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/ede95637e4cbcbd3b8b5a4359fcf0b82?time=last-seven-days&sessionEventKey=601A318E02520001109CCC37854369F0_1503349217606816638

**Comment by rtsisyk** [comment]
OK, this is non-fetal error.
