### ISSUE TITLE
[Android] NPE in com.mapswithme.maps.bookmarks.BookmarksCatalogFragment.onCreateView

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#144]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.omaps.debug/com.mapswithme.maps.bookmarks.BookmarksCatalogActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapswithme.maps.purchase.BillingManager.initialize(android.app.Activity)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
 ```
 
 ```
 Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapswithme.maps.purchase.BillingManager.initialize(android.app.Activity)' on a null object reference
       at com.mapswithme.maps.bookmarks.BookmarksCatalogFragment.onCreateView(BookmarksCatalogFragment.java:188)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
       at com.mapswithme.maps.base.BaseMwmFragmentActivity.onStart(BaseMwmFragmentActivity.java:187)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
       at android.app.Activity.performStart(Activity.java:7108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
 ```
 
 https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/9f08e3e76d61ec0c46910678a1c57ba9?time=last-seven-days&sessionEventKey=6023788B017200011F0F80858056CBFF_1505958873165165033

**Comment by rtsisyk** [comment]
This problem happened during development.
