### ISSUE TITLE
[Android]  A crash on Google Sign In

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#145]
```
Fatal Exception: java.lang.IllegalArgumentException: Given String is empty or null
       at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@17.1.1:5)
       at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.zac(:52)
       at com.google.android.gms.auth.api.signin.GoogleSignInOptions$Builder.requestIdToken(:28)
       at com.mapswithme.maps.auth.SocialAuthDialogFragment.onCreate(SocialAuthDialogFragment.java:92)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
       at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/9190d5880f0955853eb50b9b8bc3befb?time=last-seven-days&sessionEventKey=601CF8FF02520001745E336242245604_1504144850239310257

**Comment by rtsisyk** [comment]
I think that "com.mapswithme.maps.auth.SocialAuthDialogFragment" must never be called. It is used by bookmark sync which is disabled.

**Comment by rtsisyk** [comment]
This problem happened during development.
