### ISSUE TITLE
[Android] NPE in com.mapswithme.maps.purchase.PurchaseController.initialize(java.lang.Object)

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#146]
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapswithme.maps.purchase.PurchaseController.initialize(java.lang.Object)' on a null object reference
       at com.mapswithme.maps.MwmActivity.initControllersAndValidatePurchases(MwmActivity.java:646)
       at com.mapswithme.maps.MwmActivity.onSafeCreate(MwmActivity.java:603)
       at com.mapswithme.maps.base.BaseMwmFragmentActivity.onCreate(BaseMwmFragmentActivity.java:86)
       at android.app.Activity.performCreate(Activity.java:7088)
       at android.app.Activity.performCreate(Activity.java:7079)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/7d58e75faa0b6cceee1f846912c9bb92?time=last-seven-days&sessionEventKey=6022D6DC0357000117D284533A1851F7_1505781075909836917

**Comment by rtsisyk** [comment]
This problem happened during development.
