### ISSUE TITLE
[Android] NotFoundException: Drawable app.omaps.debug:drawable/ic_img_whatsnew_lp

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#147]
```
Caused by android.content.res.Resources$NotFoundException: File res/drawable/ic_img_whatsnew_lp.xml from drawable resource ID #0x7f08020e
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:837)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:638)
       at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:316)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:891)
       at android.content.res.Resources.getDrawable(Resources.java:833)
       at android.content.Context.getDrawable(Context.java:614)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:455)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
       at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
       at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:90)
       at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:98)
       at com.mapswithme.maps.onboarding.BaseNewsFragment$Adapter.instantiateItem(BaseNewsFragment.java:152)
       at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:22105)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:727)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2467)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1806)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
       at android.view.Choreographer.doCallbacks(Choreographer.java:841)
       at android.view.Choreographer.doFrame(Choreographer.java:772)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

```
Caused by org.xmlpull.v1.XmlPullParserException: no path defined
       at android.graphics.drawable.VectorDrawable.inflateChildElements(VectorDrawable.java:784)
       at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:639)
       at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
       at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
       at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1254)
       at android.content.res.ResourcesImpl.createFromXmlForDensity(ResourcesImpl.java:1471)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:822)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:638)
       at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:316)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:891)
       at android.content.res.Resources.getDrawable(Resources.java:833)
       at android.content.Context.getDrawable(Context.java:614)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:455)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
       at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
       at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
       at androidx.appcompat.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:90)
       at androidx.appcompat.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:98)
       at com.mapswithme.maps.onboarding.BaseNewsFragment$Adapter.instantiateItem(BaseNewsFragment.java:152)
       at androidx.viewpager.widget.ViewPager.addNewItem(ViewPager.java:1010)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1158)
       at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
       at android.view.View.measure(View.java:22105)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:958)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6606)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:727)
       at android.view.View.measure(View.java:22105)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2467)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1806)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
       at android.view.Choreographer.doCallbacks(Choreographer.java:841)
       at android.view.Choreographer.doFrame(Choreographer.java:772)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.debug/issues/2d2f4a5e39b605e676752f00b1c47425?time=last-seven-days&sessionEventKey=602127D6008100010887E10AC1C8CACE_1505307401541259665

**Comment by rtsisyk** [comment]
This problem happened during development.
