### ISSUE TITLE
[Android] NPE in om.mapswithme.maps.MwmApplication.from

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#155]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at com.mapswithme.maps.MwmApplication.from(MwmApplication.java:123)
       at com.mapswithme.util.CrashlyticsUtils.checkCrashlytics(CrashlyticsUtils.java:38)
       at com.mapswithme.util.CrashlyticsUtils.logException(CrashlyticsUtils.java:22)
       at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:321)
       at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:255)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.beta/issues/8da9405ad6b9caccd22c4b5c55366641?time=last-seven-days&sessionEventKey=602BF7B800E300012356CC52B104BACB_1508350428385340551

**Comment by rtsisyk** [comment]
Should be fixed in 10.6.0.
