### ISSUE TITLE
[Android] Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference

### ISSUE THREAD

**Issue by maxbraunschmied** [omapsapp/omapsapp#195]
I tried running it but it crashes on startup with following logs:

	Fatal Exception:java.lang.RuntimeException: An error occurred while executing doInBackground()
		at android.os.AsyncTask$4.done(AsyncTask.java:415)
		at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
		at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
 		at java.util.concurrent.FutureTask.run(FutureTask.java:271)
 		at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		at java.lang.Thread.run(Thread.java:923)

	Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
		at com.mapswithme.maps.MwmApplication.from(MwmApplication.java:123)
 		at com.mapswithme.util.CrashlyticsUtils.checkCrashlytics(CrashlyticsUtils.java:38)
 		at com.mapswithme.util.CrashlyticsUtils.logException(CrashlyticsUtils.java:22)
 		at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:321)
 		at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:255)
 		at android.os.AsyncTask$3.call(AsyncTask.java:394)
 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 		... 4 more``

**Comment by rtsisyk** [comment]
This problem should be fixed in 10.6.0.
