### ISSUE TITLE
[Android]: java.net.MalformedURLException: no protocol on the start

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#281]
```
04-03 10:20:35.141 18066 18066 D MapsmeCore: maps/DownloadResourcesLegacyActivity.cpp:213 Java_com_mapswithme_maps_DownloadResourcesLegacyActivity_nativeStartNextFileDownlo
ad()  downloading 07_roboto_medium.ttf sized 162588 bytes
04-03 10:20:35.149 18066 23563 E ChunkTask: Invalid url:
04-03 10:20:35.149 18066 23563 E ChunkTask: java.net.MalformedURLException: no protocol:
04-03 10:20:35.149 18066 23563 E ChunkTask:     at java.net.URL.<init>(URL.java:601)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at java.net.URL.<init>(URL.java:498)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at java.net.URL.<init>(URL.java:447)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at com.mapswithme.maps.downloader.ChunkTask.doInBackground(ChunkTask.java:139)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at com.mapswithme.maps.downloader.ChunkTask.doInBackground(ChunkTask.java:24)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-03 10:20:35.149 18066 23563 E ChunkTask:     at java.lang.Thread.run(Thread.java:923)
04-03 10:20:35.178 18066 23462 W libEGL  : EGLNativeWindowType 0x7934f694b0 disconnect failed
```

**Comment by rtsisyk** [comment]
I added TTF resources back to all flavors.

**Comment by biodranik** [comment]
Ты скорее всего собрал опенсорс версию без урла на загрузку.
