### ISSUE TITLE
Android: attempt to invoke android.content.Context.getApplicationContext() on a null object reference

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#86]
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.mapswithme.maps.location.TrackRecorderWakeReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4238)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at com.mapswithme.maps.MwmApplication.backgroundTracker(MwmApplication.java:129)
       at com.mapswithme.maps.location.TrackRecorder.onWakeAlarm(TrackRecorder.java:160)
       at com.mapswithme.maps.location.TrackRecorderWakeReceiver.onReceive(TrackRecorderWakeReceiver.java:26)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4229)
       at android.app.ActivityThread.access$1700(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2113)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
```

https://console.firebase.google.com/u/0/project/omapsapp/crashlytics/app/android:app.omaps.beta/issues/8da9405ad6b9caccd22c4b5c55366641?time=last-seven-days&sessionEventKey=602BF7B800E300012356CC52B104BACB_1508350428385340551

**Comment by rtsisyk** [comment]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at com.mapswithme.maps.MwmApplication.from(MwmApplication.java:123)
       at com.mapswithme.util.CrashlyticsUtils.checkCrashlytics(CrashlyticsUtils.java:38)
       at com.mapswithme.util.CrashlyticsUtils.logException(CrashlyticsUtils.java:22)
       at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:321)
       at com.mapswithme.maps.analytics.ExternalLibrariesMediator$GetAdInfoTask.doInBackground(ExternalLibrariesMediator.java:255)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
 ```

**Comment by rtsisyk** [comment]
This problem is still actual.
